#!/usr/bin/with-contenv bash
#shellcheck shell=bash

rm /var/run/dbus/pid > /dev/null 2>&1 || true
dbus-daemon --system --nofork 2>&1 | stdbuf -o0 awk '{print "[dbus-daemon] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
