name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  test_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Docker Build
      run: docker build --no-cache . --file Dockerfile
